services:
 db:
  #  docker_name: postgres
   image: postgres
   restart: always
   environment:
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?database password not set}
   volumes:
     - postgres-data:/var/lib/postgresql/data
 adminer:
  #  docker_name: adminer
   image: adminer
   restart: always
   ports:
     - 8080:8080
 app:
  #  docker_name: Program
   build:
     context: .
   ports:
     - 5000:80
   depends_on:
     - db
volumes:
 postgres-data: